module Const

	STREET_TYPES = [
		['Way', 'WY'],
		['Avenue', 'AV'],
		['Lane', 'LN'],
		['Bend', 'BN'],
		['Alley', 'AL'],
		['Bypass', 'BY'],
		['Circle', 'CR'],
		['Court', 'CT'],
		['Extension', 'EX'],
		['Highway', 'HY'],
		['Junction', 'JT'],
		['Park', 'PK'],
		['Parkway', 'PY'],
		['Place', 'PL'],
		['Square', 'SQ'],
		['Terrace', 'TR'],
		['Turnpike', 'TP'],
		['Street', 'ST'],
		['Boulevard', 'BV'],
		['Trail', 'TL'],
		['Path', 'PT'],
		['Road', 'RD'],
		['Route', 'RT'],
		['Drive', 'DR']
	]
	
	STREET_DIRS = [
		['North', 'N'],
		['Northeast', 'NE'],
		['East', 'E'],
		['Southeast', 'SE'],
		['South', 'S'],
		['Southwest', 'SW'],
		['West', 'W'],
		['Northwest', 'NW'],
	]
	
	US_STATES = [ 
		['New York', 'NY'], 
		['Alabama', 'AL'], 
		['Alaska', 'AK'], 
		['Arizona', 'AZ'], 
		['Arkansas', 'AR'], 
		['California', 'CA'], 
		['Colorado', 'CO'], 
		['Connecticut', 'CT'], 
		['Delaware', 'DE'], 
		['District Of Columbia', 'DC'], 
		['Florida', 'FL'], 
		['Georgia', 'GA'], 
		['Hawaii', 'HI'], 
		['Idaho', 'ID'], 
		['Illinois', 'IL'], 
		['Indiana', 'IN'], 
		['Iowa', 'IA'], 
		['Kansas', 'KS'], 
		['Kentucky', 'KY'], 
		['Louisiana', 'LA'], 
		['Maine', 'ME'], 
		['Maryland', 'MD'], 
		['Massachusetts', 'MA'], 
		['Michigan', 'MI'], 
		['Minnesota', 'MN'], 
		['Mississippi', 'MS'], 
		['Missouri', 'MO'], 
		['Montana', 'MT'], 
		['Nebraska', 'NE'], 
		['Nevada', 'NV'], 
		['New Hampshire', 'NH'], 
		['New Jersey', 'NJ'], 
		['New Mexico', 'NM'], 
		['North Carolina', 'NC'], 
		['North Dakota', 'ND'], 
		['Ohio', 'OH'], 
		['Oklahoma', 'OK'], 
		['Oregon', 'OR'], 
		['Pennsylvania', 'PA'], 
		['Rhode Island', 'RI'], 
		['South Carolina', 'SC'], 
		['South Dakota', 'SD'], 
		['Tennessee', 'TN'], 
		['Texas', 'TX'], 
		['Utah', 'UT'], 
		['Vermont', 'VT'], 
		['Virginia', 'VA'], 
		['Washington', 'WA'], 
		['West Virginia', 'WV'], 
		['Wisconsin', 'WI'], 
		['Wyoming', 'WY']
	]

end