# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 88d0ed36ae99e83490204607520714fa8f60b8bc9e34c4d70bb6315b75aec9cd7bf693549ea0fe1a99faa6f82f6a4bfa4509da9a4ee43f9b1456bdbd95de89a5
  google_info: {"Customer A": {"API Key" : "AIzaSyCI33WirMl2FJlzwi5vey0C8T63qnFh4Jg", "type": "atm", "language": "English", "response output": "xml","number of locations": 200}, "Customer B": {"API Key": "AIzaSyCI33WirMl2FJlzwi5vey0C8T63qnFh4Jg","type": "bank","language": "Spanish","response output": "json","number of locations": 20}, "Customer C": {"API Key": "AIzaSyCI33WirMl2FJlzwi5vey0C8T63qnFh4Jg","type": "all","language": "French","response output": "json","number of locations": 5}}
  
test:
  secret_key_base: b60380d7223bb1a948da108170d6229a28fcbbfaa36d1844fcc04a762192f588995c13be4bd0cacc3d60da787b0eeb43c029955397b4b7e89aa8484d0349b154

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
